
tasks:
  - init: npm install
    command: npm start
  - command: npm test
ports:
  - port: 8080
    onOpen: open-browser
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - eg2.vscode-npm-script
